parameters:
    # Settings manager.
    ongr_settings.settings_manager.class: ONGR\SettingsBundle\Settings\General\SettingsManager

    ongr_settings.settings_container.class: ONGR\SettingsBundle\Settings\General\SettingsContainer
    ongr_settings.setting_aware_service_factory.class: ONGR\SettingsBundle\Settings\General\SettingAwareServiceFactory
    ongr_settings.listener.cookie_profile.class: ONGR\SettingsBundle\EventListener\ProfileRequestListener
    ongr_settings.profiles_manager.class: ONGR\SettingsBundle\Settings\Personal\ProfilesManager

    ongr_settings.settings_provider.class: ONGR\SettingsBundle\Settings\General\Provider\ManagerAwareSettingProvider

    ongr_settings.settings_provider_es_manager: es.manager

services:
    ongr_settings.settings_manager:
        class: %ongr_settings.settings_manager.class%
        arguments:
            - @translator
            - @event_dispatcher
            - @es.manager

    ongr_settings.settings_container:
        class: %ongr_settings.settings_container.class%
        arguments:
            - @stash
            - %ongr_settings.settings_container.profiles%
        tags:
            - { name: kernel.event_listener, event: ongr_settings.setting_change, method: onSettingChange }

    ongr_settings.setting_aware_service_factory:
        class: %ongr_settings.setting_aware_service_factory.class%
        arguments:
            - @ongr_settings.settings_container
        calls:
            - [ setLogger, [ @?logger ] ]
        tags:
            - { name: monolog.logger, channel: admin }

    ongr_settings.listener.cookie_profile:
        class: %ongr_settings.listener.cookie_profile.class%
        calls:
            - [ setSettingsContainer, [ @ongr_settings.settings_container ] ]
            - [ setPersonalSettingsManager, [ @ongr_settings.settings.personal_settings_manager ] ]
            - [ setManager, [ @es.manager ] ]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    ongr_settings.profiles_manager:
        class: %ongr_settings.profiles_manager.class%
        arguments:
            - @es.manager
